version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flaskbackend
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    volumes:
      - ./documentation:/documentation

  nginx:
    build: ./nginx
    container_name: nginxbackend
    restart: always
    ports:
      - "80:80"
